### ISSUE TITLE
Docker mount point for data so that data is not gone when container exisits

### ISSUE THREAD

**Issue by Abhijit-2592** [chakki-works/doccano#120]
If I run the tool using Docker, where is the mount point for the data so that we don't loose data when container is removed

**Comment by c-w** [comment]
The default location for the database SQLite file is `/doccano/app/db.sqlite3` so you can mount that path in order to preserve the state across container restarts.

Alternatively you can also run the container and set the environment variable `DATABASE_URL` to point doccano to an external database such as Postgres or MySQL. This is for example what the Azure deployment does in order to preserve state across container restarts and across potentially multiple replicas of the container: see for reference the [setting of the environment variable](https://github.com/chakki-works/doccano/blob/61c50699348321db7a26f8df5b80706c2c5390a6/azuredeploy.json#L206-L207) and the [database connection string](https://github.com/chakki-works/doccano/blob/61c50699348321db7a26f8df5b80706c2c5390a6/azuredeploy.json#L100).

**Comment by Abhijit-2592** [comment]
Thanks.This is an awesome tool

**Comment by icoxfog417** [comment]
@c-w Thank you for your nice advice!

**Comment by Zylatis** [comment]
Hey, apologies for thread necro. I am having some trouble extracting the db file using docker mount. If i try ```docker run -d --name doccano -p 8000:8000 -v $(pwd):/app chakkiworks/doccano``` i don't seem to get access to that directory. I have also tried using docker volumes but that didn't seem to work, though probably I am doing it wrong.

What is the correct way to go about running this container so I can have access to the .db file from the host?

Thanks!

**Comment by c-w** [comment]
@Zylatis The code is mounted at `/doccano` ([see Dockerfile](https://github.com/chakki-works/doccano/blob/1c4894af9d75d3b76e1802f38d2739c4302ddfc4/Dockerfile#L37)) so could you try setting the mount point to something like `-v $(pwd):/doccano`?

**Comment by Zylatis** [comment]
@c-w Thanks for info, i had tried that before and get
```docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/doccano/tools/run.sh\": stat /doccano/tools/run.sh: no such file or directory": unknown.
```

**Comment by c-w** [comment]
@Zylatis I'm assuming the "no such file or directory" error happens because you're running the docker container outside of the root of the Doccano source tree (which means that the volume mount will override the source tree in the container so the `run.sh` script is missing). If so, you may try scoping the volume mount command to only include the database file via something like this: `docker run -v $(pwd)/doccano.db:/doccano/app/db.sqlite3 ...`

**Comment by platinum736** [comment]
I tried above technique to use mounted file system. Though it worked for django server level data but it is not taken by doccano application. Is there anything else I need to do.

**Comment by PATELS2R** [comment]
I am a little naive but seems like people are talking in hints. Sure there might me some obvious things, but would it wouldn't hurt to give a detailed answer.
**My concern** - When using option 1 (docker-compose ... up) how to make sure that the database is stored in local file system (contrary to docker environment)
**Motivation** - To make data backups easy. Also to ensure that data persists in case the docker container is deleted or re-spawned at some other location.
