### ISSUE TITLE
Feature Request: Upload/Download data from Cloud Storage directly

### ISSUE THREAD

**Issue by icoxfog417** [chakki-works/doccano#141]
Recently, many user will have their data on cloud storage like S3/GCS etc.

For that reason, it'll be good to upload data from cloud storage directly, and also save annotated data to it. If this feature implemented, there are no need to have the data on local.

**Comment by c-w** [comment]
Great idea. I would recommend to use the [Apache libcloud](https://github.com/apache/libcloud) library which offers a unified interface to many storage providers like AWS, Azure, GCP, etc.

**Comment by bahiamartins** [comment]
Use django storages and you are good to go. https://django-storages.readthedocs.io/en/latest/

**Comment by c-w** [comment]
@Hironsan @icoxfog417 This feature will be very useful for one of my upcoming projects, so I'd like to start working on implementing it.

Here are my initial thoughts, please let me know what you think so that we're aligned on how to best build this feature.

I was thinking of adding a new button next to the file upload button to trigger the cloud upload feature:

![Mock-up of cloud upload workflow 1](https://user-images.githubusercontent.com/1086421/57858898-e8d14b00-77bf-11e9-9ffb-4bcad2cf73b1.png)

This button can open a modal that lets the user input all the data required to connect to the cloud storage via [Apache Libcloud](https://github.com/apache/libcloud):

![Mock-up of cloud upload workflow 2](https://user-images.githubusercontent.com/1086421/57858909-ee2e9580-77bf-11e9-8b67-2b9772ca33c8.png)

When the user clicks the upload button, the form is sent to the TextUploadAPI. In this request, there will be no file present so the backend API checks for that. If the file is not present, the API opens the cloud file as a stream and passes it to the parser. The rest of the code doesn't have to change. Something along these lines:

```py
class TextUploadAPI(APIView):
  # ... the code before this point doesn't have to change

  def post(self, request, *args, **kwargs):
        project = get_object_or_404(Project, pk=self.kwargs['project_id'])

        if 'file' in request.data:
            data = request.data['file']
        else:
            libcloud_connector = ... # code to unpack libcloud fields here
            data = ... # code to open file from cloud storage as stream here

        parser = self.select_parser(request.data['format'])
        data = parser.parse(data)
        # ... the rest of the code below this point doesn't have to change
```

One benefit of this approach is that the cloud upload piece is completely decoupled from the rest of the Django configuration so for each upload the user could select a different cloud storage, e.g. import one set of data from AWS S3 and another from Google Cloud Storage.

Let me know what you think!

**Comment by c-w** [comment]
See https://github.com/chakki-works/doccano/pull/213 for an implementation of cloud data import via [django-cloud-browser](https://github.com/ryan-roemer/django-cloud-browser).

**Comment by echan00** [comment]
Just tried out this feature, seems like transfer from AWS still timesout on Heroku 😢

**Comment by c-w** [comment]
@echan00 I suspect the timeout will be solved by implementing an approach like https://github.com/chakki-works/doccano/issues/241#issuecomment-508139685 which moves the generation of the export file out of the HTTP loop and into a background worker.
