### ISSUE TITLE
Support importing datasets in JSON format

### ISSUE THREAD

**Issue by Zerthick** [chakki-works/doccano#17]
Currently in order to upload a dataset for annotation all of the documents in the dataset must be in a single txt file with each document separated by a newline character like so:
```
document 1 text
document 2 text
```
It would be very helpful if instead documents could be within separate files and a bulk upload could be performed.  For example:

**Document 1**
```
Document
1
text
```

**Document 2**
```
Document
2
text
```

This would also allow documents to contain newline characters which was requested here: #12 

Love the tool!

**Comment by Zerthick** [comment]
Alternatively, supporting uploading a single file in JSON format such as:
```JSON
[
"Document 1 text",
"Document 2 text"
]
```

Would also work.

**Comment by Zerthick** [comment]
I've created a bare-bones implementation of this second approach utilizing a single JSON file here:
https://github.com/Zerthick/doccano/pull/1

It currently adds a second radio button to allow the user to specify which format file they would like to upload, however this could be changed to infer the format based on the file name extension.

In addition, this method of upload allows documents to contain both newline characters and commas within their text, meaning the rendering of the annotation views should support this behavior.

**Comment by icoxfog417** [comment]
Thank you for your proposal! Certainly supporting one-data-one-file format (like jsonl) is good for the data including newline or complex structure.

When supporting this feature, I think it will be good to enable uploading archived file (like `tar.gz` or `zip`). We contine to improve the way to upload the data.

**Comment by Zerthick** [comment]
I agree, uploading a `tar.gz` archive would be helpful as well.

**Comment by Zerthick** [comment]
So is there a consensus on the format of the JSON file? I can update the parser as needed.  Also, is the separate radio button an acceptable way to implement this functionality in the UI, or would we want to auto-detect based on file extension?  Finally, if the user uploads a zip or tar file should it be expected that the archive contains a single file and if so, what is the format of that file, CSV, JSON, both?

**Comment by BrambleXu** [comment]
@Zerthick, thanks for your advice. We had a discussion about your request and I will share it with you. 

* So is there a consensus on the format of the JSON file? 
  * Yes, we want to support the JSON file. 

* Also, is the separate radio button an acceptable way to implement this functionality in the UI, or would we want to auto-detect based on file extension? 
  * The radio button is a great idea, we will accept it.

* Finally, if the user uploads a zip or tar file should it be expected that the archive contains a single file and if so, what is the format of that file, CSV, JSON, both?
  * Right now, we want to support the JSON file first. After we finish the JSON support part, we can open a new issue to talk about supporting the zip or tar file. 

---

* As for the JSON format. You mentioned JSON format such as:
```
[
    "Document 1 text",
    "Document 2 text"
]
```
This format is pretty the same with the txt format file. In such case, we recommend you use the txt format to upload your file. And in order to make full use of JSON format, we set the JSON format like `demo1.json` below:
```
{'text': 'this is the first text'}
{'text': 'this is the second text'}
```
The key should be set as `text`, and the value is the document we want to annotate. The reason why we set this format is that we want to support the #11 Import labeled dataset in the future. In such case, we can import JSON like `demo2.json` below:
```
{'text': 'this is the first text', 'label': xxxx }
{'text': 'this is the second text', 'label', xxxx}
```
The label format will be different regarding the project/task. But first we want to support the JSON format like `demo1.json`.

---

The JSON file should work in three project/task (sequence labeling, document classification, sequence to sequence). But for the sequence labeling task, the document is supposed contain no newline. Becasue this will cause the UI changed in the sequence labeling anotation page. For other two tasks, it is ok that the document contains newline. 

I upload two demo json file for test, feel free to use it.
[test_json_NER.json](https://drive.google.com/open?id=1Fhr3xBmfdUbtLko9Prd-ZtsUQl6SWERA)
[test_json_NER_newline.json](https://drive.google.com/open?id=1FdSrY_GADnGiA-wPZnpleZIntkkqQyYo)

If you have any question, let me know :)

**Comment by Zerthick** [comment]
If you would like to support a more sophisticated JSON schema would you rather just utilize the format used by spaCy?

In that format your demo text would look like so:

```json
[
	[
		"this is the first text",
		{
			"cats": {
				"label1": true,
				"label2": false
			}
		}
	],
	[
		"this is the second text",
		{
			"cats": {
				"label1": false,
				"label2": true
			}
		}		
	]
]
```

This has the benefit of allowing text to have more than one label attached to it.

**Comment by Zerthick** [comment]
Ok, in that case I'd suggest making your format a valid JSON list, as it will be easier to generate and load in python scripts, so something like:

```JSON
[
    {'text': 'this is the first text'},
    {'text': 'this is the second text'}
]
```

**Comment by BrambleXu** [comment]
In such a format, we have to load the whole JSON file at once. If the file has big size, this would use a lot of memory. That's why we want to make the JSON format as simple as possible to read the file line by line, which can avoid big memory usage.

**Comment by Zerthick** [comment]
Ok makes sense, I rework my parser accordingly.  How would you like to handle multiple labels?

Would you do something like:
```json
{"text": "this is the first text", "label": ["label1", "label2"] }
```
Or something like:
```json
{"text": "this is the first text", "label1": true, "label2": true }
```
Or something else?

**Comment by BrambleXu** [comment]
As for the label format, we will discuss it later.  But there should be a `label` key contains all label information, which is like the first example you list.

**Comment by Zerthick** [comment]
Understood, I'll just work on parsing the `text` key for now then.

**Comment by BrambleXu** [comment]
Hi @Zerthick, thanks for your advice. Right now you can upload json file to doccano. Next we will work on the #27 to make linebreak possible.
