### ISSUE TITLE
View metadata next to a document in sequence labeling

### ISSUE THREAD

**Issue by prokotg** [chakki-works/doccano#174]
Hi guys! The idea of adding metadata to a document and keeping it while exporting is great. Sometimes though, a quick glance at these metadata while working on a document would be just a game changer. I recommend adding button "Peek metadata".  Would you consider adding such feature in next releases?

Thank you :-)

**Comment by c-w** [comment]
In my opinion this is a great suggestion. The "peek metadata" feature will be especially useful for annotation projects where the source of the text may be diverse (e.g. text extracted from DOCX or PDF, text extracted from images via OCR, etc.) so that the annotated text can be linked back to the source.

I've implemented this in #200 using a modal like we already have in use for the annotation guideline. I'm struggling a bit to find a good icon to represent the concept of metadata though. Does anyone have suggestions for which icon to use? For reference, here is the list of all the icons that should be available to doccano: https://fontawesome.com/icons?d=gallery&m=free
