### ISSUE TITLE
Versioning for docker images

### ISSUE THREAD

**Issue by maneo** [chakki-works/doccano#182]
Current script responsible for building docker images tools/cd.sh builds image with {TRAVIS_TAG} and as LATEST. The problem is that {TRAVIS_TAG} is filled only when git commit is tagged, which no one is doing here :-). As a result images at dockerhub can only be found as latest, it is impossible to refer to a fixed version. What do you think about changing (or adding one more) build with {TRAVIS_COMMIT}  as version?  This might help in avoiding non obvious errors when latest version will be different on local machine (outdated) and on CI server.

**Comment by c-w** [comment]
Chiming in here since I wrote the initial version of the `cd.sh` script: sounds like a great idea. We can even have the best of both worlds by publishing a new image on every master build and then a more "official" image on tags/releases. I've submitted a pull request for this here: https://github.com/chakki-works/doccano/pull/184.
