### ISSUE TITLE
Feature Request: Control sort order on the front end

### ISSUE THREAD

**Issue by jamesmf** [chakki-works/doccano#20]
### Describe the problem
In order to facilitate smarter labeling, it would be great if there were methods for re-ordering the documents based on specific criteria. Some basic orders might be:
- max( abs(annotation.prob - 0.5)) asc
  - this would order by the least certain predicted annotations
- document insertion date
- most/least recently updated (manual) annotation

### Source code / logs
https://github.com/chakki-works/doccano/blob/master/app/server/api.py#L102
Seems like if a few more things got checked in the `get_queryset` def here, we could potentially allow you to either 
1) set sort-order at a project level
2) re-sort using a button

**Comment by rbagd** [comment]
Another type of order that would be useful is randomized order per user. It's necessary for statistical control to make sure that in case of multiple annotators, _annotation fatigue_ doesn't affect the labels themselves so that sorting is done, for example, based on the hash of `user_id` and `doc_id`.

**Comment by c-w** [comment]
@BatslyAdams is working on this.
