### ISSUE TITLE
Code: what is the demo folder?

### ISSUE THREAD

**Issue by clarus** [chakki-works/doccano#274]
I have a question about the code of Doccano. There is a folder https://github.com/chakki-works/doccano/tree/master/app/server/static/components/demo which includes some demo components, as well as `.js` files about these components. What are they used for? Do they create code duplication with the non-demo components?

**Comment by c-w** [comment]
The `demo` folder renders the three live demo pages that prospective users can use to evaluate Doccano:

![Screenshot of demo page menu](https://user-images.githubusercontent.com/1086421/60736159-00a58f80-9f24-11e9-830a-80cfb4023101.png)

It is true that the code is somewhat duplicated with the main annotation canvas. Ideally we'd refactor the annotation canvas to extract the API integrations so that the code can be shared between production pages (HTTP API interactions) and demo pages (fake in-memory API interactions).

**Comment by c-w** [comment]
I'll look a bit into this. Should be a nice refactor.
