### ISSUE TITLE
Ask for confirmation before deleting a project/label

### ISSUE THREAD

**Issue by miskolc** [chakki-works/doccano#314]
It appears to me that deleting a project or a label is way too easy if you accidentally click the delete button. Please add a pop up asking for confirmation.

**Comment by echan00** [comment]
agreed!

**Comment by rjendoubi** [comment]
Hi @miskolc, looks like there is already a confirm pop-up for deleting a project:

![image](https://user-images.githubusercontent.com/13799723/66863363-c1f38c80-ef8a-11e9-90d5-49b0a7f859a5.png)

This basic functionality seems to have been in place since 4ab558df4489acb9f67919e759c971d40359a756 (it's undergone a number of refactors since then).

When you refer to confirming on deleting a label, do you mean simply deleting an _instance of_ a label?

![image](https://user-images.githubusercontent.com/13799723/66863670-6e357300-ef8b-11e9-8278-9402ec7659c0.png)

Or is it a different context that you mean?

**Comment by Hironsan** [comment]
Resolved.

After [ver 1.0.0](https://github.com/chakki-works/doccano/releases/tag/v1.0.0), ask for confirmation before deleting a project/label/documents.
