### ISSUE TITLE
How to query a HTTP GET by annotation_approver property

### ISSUE THREAD

**Issue by ayrtondenner** [chakki-works/doccano#335]
I'm trying to implement a feature to query data that hasn't been approved yet. I managed to successfully add an option in front-end, specifically in annotation.pug file. But I didn't get how to query documents where annotation_approver property is null. I'm trying to do it via Postman, using queries like `http://localhost:8000/v1/projects/12/docs?limit=5&seq2seq_annotations__isnull&q=annotation_approver:admin` or `http://localhost:8000/v1/projects/12/docs?limit=5&seq2seq_annotations__isnull&annotations_approved_by=admin`, but neither worked.

**Comment by c-w** [comment]
The API behind the docs endpoint is [DocumentList](https://github.com/chakki-works/doccano/blob/fa9ae3b1f3d38cf5cf97686f89212b174d9ec4e1/app/api/views.py#L128). I believe in order to enable querying by extra fields, you'll need to whitelist them in [DocumentFilter](https://github.com/chakki-works/doccano/blob/fa9ae3b1f3d38cf5cf97686f89212b174d9ec4e1/app/api/filters.py#L8-L10).
