### ISSUE TITLE
Feature Request: Add document metadata

### ISSUE THREAD

**Issue by serzh** [chakki-works/doccano#45]
### Describe the problem
It would be nice if it possible to import some examples metadata while importing the dataset. For now it is possible only to import the text, but in my expirience I rarely need only text. I often need some external id, source, etc to be passed into the annotation tool along the text. And it would be nice to have it within my exported dataset.

**Comment by BrambleXu** [comment]
Please give us more detail of your problem.
* Which task you need to import your metadata? Document classification? Sequence labeling? Sequence to sequence? Or all of them.
* If you often import external information, what kind of data format you use? Json?
* In the export data, take classification task as an example, you can find the document id, text, label, username. Is this not enough for your task?

**Comment by serzh** [comment]
Sure, thanks for rapid feedback!

My task now is to provide annotations for several steps in the ML pipeline for information extraction. But it is not limited to my setup. I will try to describe more precisely when this problem arises.

Let's imagine you have a not annotated dataset, which contains some metadata for each example: id, source, date for creation, user that grabs it, etc. Now you want to use `doccano` to annotate it. To be able to match the initial dataset with annotated you need, at least, some `external_id` that is imported with your dataset into the `doccano`. 

I see two usages for doccano:
* source of truth for datasets and annotation tool
* annotation tool

And for both of them you need to have some metadata to be stored with your examples. 
It does not matter what type of task you are accomplishing and what is the format of you dataset. I see this as a generally usefull feature.

**Comment by serzh** [comment]
It is not well documented but Explosion's annotation tool Prodigy does have this feature https://support.prodi.gy/t/how-to-incorporate-document-metadata/296/2

**Comment by BrambleXu** [comment]
Thanks for your supplement. 
Your request does make sense. We do not consider such metadata like data source, user who grabs and so on. But doccano is a light annotation tool, it would be a nightmare to consider all kind of metadata. 

However, as you said, if there is at least the `external_id` with imported file and export file, you can align the data by yourself after you get the annotated file. It is a good idea. We will consider your request.

**Comment by serzh** [comment]
>  user who grabs and so on. But doccano is a light annotation tool
We can take an approach used by Prodigy tool: just store all *other* fields into the json column in database at import phase and merge it on the export phase.

**Comment by BrambleXu** [comment]
If we consider the `context` (many kinds of metadata), it may change the model classes a lot in `models.py`. I use 'light' to means a minimal modification to model classes and a few of fields in the database. Either way, I will talk with @Hironsan and decide which approach to use.

**Comment by serzh** [comment]
If you will need a PR I will happily provide you one.

**Comment by BrambleXu** [comment]
Thanks @serzh, I saw your work on metadata feature, and it's great!  
Could you PR it after this #46 merged? This PR implement the json export feature from front to end. And the code may conflict with yours in the `views.py`. 
After it is merged, you could make a little modification in your code and then make a PR. Our reviewer will give the review.

**Comment by serzh** [comment]
Sure 👍

**Comment by BrambleXu** [comment]
Hi, @serzh, thanks for your patience. We have implemented the JSON export feature from front to end. Could you change your code accordingly? 
In order to follow a good GitHub collaboration workflow, there are some tips might be helpful. 

Usually, we use a new branch for feature development. But you developed directly on the master branch. This will cause confilct when you want to merge latest version to your forked repo. 

In order to rebase your forked repo (master branch) to the latest version of doccano. You should make a copy of your code, where the code related with metadata feature. 

```
# Add upstream
git remote add upstream https://github.com/chakki-works/doccano

# Fetch all the branches of that remote into remote-tracking branches,
git fetch upstream

# Make sure that you're on your master branch:
git checkout master

# Rewrite your master branch to make  your local doccano be the same with upstream/master 
git reset --hard upstream/master

# Make your forked repo same as the upstream
git push -f origin master
```
`git reset --hard upstream/master` will make your local version totally same with doccano master branch and delete the work you have committed. So, please make a copy before running the `git reset --hard upstream/master`.  

After you update your local master and origin master same with the upstream master, you can name a new branch like: `git checkout -b feature/metadata`. 

Then you could rewrite the metadata feature code in the `feature/metadata` branch. Here you will use the copied code before running `git reset --hard upstream/master`. 

After you finish the development, you can run `git push origin feature/metadata` and make a PR from `serzh:feature/metadata` to `chakki-works:master`. 

If you have any questions feel free to ask us.

**Comment by serzh** [comment]
@BrambleXu Thanks, will start working on it
