### ISSUE TITLE
Can not add new user to a project

### ISSUE THREAD

**Issue by jonhilgart22** [chakki-works/doccano#452]
How to reproduce the behaviour
---------

Create a new project as the admin user, create a new test user and assign all permission to that user, try viewing the project created by the admin user as the new user.

Your Environment
---------

*   Operating System: Mac Mojave
*   Python Version Used: 3.7
*   When you install doccano: yesterday
*   How did you install doccano (Heroku button etc): docker-compose

I am unable to add a new 'test' user to my test project.

Here is the user setup with all permissions granted.
![image](https://user-images.githubusercontent.com/8621935/69290384-a0eb1080-0bb4-11ea-8ab4-a3b8ba90d0bd.png)

Here is an example of the project with collaborative annotation enabled.

![image](https://user-images.githubusercontent.com/8621935/69290334-83b64200-0bb4-11ea-9c03-7e28e1347e76.png)

However, when I log in as the 'test' user, I do not see the project.

![image](https://user-images.githubusercontent.com/8621935/69290408-b6f8d100-0bb4-11ea-836c-0bc491a16a6f.png)

When I log in as the admin user, I can see this project.

![image](https://user-images.githubusercontent.com/8621935/69290419-c546ed00-0bb4-11ea-9d55-466ec0c9f366.png)

Any help is appreciated
!

**Comment by jonhilgart22** [comment]
I also tried adding my test user as a `superuser`, and I am still unable to view this project that was created by the admin user.

**Comment by Hironsan** [comment]
Hello @jonhilgart22 .
Thank you for letting me know about the issue.

# Solution

1. Create a new user from the admin page.
2. Add the user to a project by the project member management page(/projects/{id}/users/).

# Analysis

* ProjectListAPI has two permission classes: `IsAuthenticated` and `IsInProjectReadOnlyOrAdmin`.
* The permissions decide whether the API returns the project list.
* If a new user is added by the admin page and logged in, `IsAuthenticated` permission is passed.
* But `IsInProjectReadOnlyOrAdmin` is not passed.
* Because the permission asks the user to have some role: project admin, annotator or approver.
* If a new user is only added by the admin page, he/she does not have any role.
* That's why the new user can not see any projects.

Have a nice day.

**Comment by jonhilgart22** [comment]
Thank you!
