### ISSUE TITLE
Rebuild js files

### ISSUE THREAD

**Issue by alohia** [chakki-works/doccano#8]
Hi,

I wish to modify some js files and then regenerate the bundle js files to get the new functionality. Can you please let me know how to go about it?

Thanks
Akhil

**Comment by icoxfog417** [comment]
doccano use [`webpack`](https://webpack.js.org/) to build js files. You can use it to build.

**Comment by abhirut** [comment]
Hi,

Could you kindly provide some more details on how to achieve this?

I guess we need to use the `webpack.config.js` file under `app/server/`, but I'm not entirely sure how to do this.

Thanks,
Abhirut

**Comment by BrambleXu** [comment]
* You should download node.js locally first, so that you can use the npm command. If you use mac, you can just run `brew install node`.  
* Then add node path to your shell path, I use zsh so I will add `export PATH=$HOME/bin:/usr/local/Cellar/node/11.1.0/bin:$PATH` to `.zshrc` file. Run `source .zshrc` and `node -v`, you should see the node version, which means you install node successfully.
* `npm install -g webpack webpack-cli` install webpack globally.
* `cd .../doccano/app/server`, run `npm install `. This will install the node module in `node_modules` folder. 
* Modify the js file in `static/js/`.
* In the `.../doccano/app/server` and run `webpack` command. You should see the js file in `static/bundle/` get changed. 

@abhirut  I covered most important parts when using webpack. If you have a different OS or environment, just Google it and you should find solutions.
